In [ ]:
%pip install pandas

In [3]:
import pandas
import numpy 

n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
matrix = n.reshape(3,9)  #Creamos una matriz de 3 x 9
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
%pip install opencv-python

In [7]:
import cv2

In [8]:
img_grices = cv2.imread("smallgray.png", 0)  #El cero indica que queremos leer la imagen en escala de grises

In [9]:
img_grices

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
img_rgb = cv2.imread("smallgray.png", 1)  #El argumento 1 es para leer la imagen en rgb

In [11]:
img_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [12]:
cv2.imwrite("newsmallgray.png", img_grices)  #Aqui lo que hicimos fue guardar la imagen en el disco duro

True

In [13]:
a = [1, 2 ,3]

In [16]:
a[0:2]  #Aqui imprimimos la primera y segunda posición de la lista

[1, 2]

In [19]:
img_2 = cv2.imread("smallgray.png", 0) 
img_2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
img_2[0:2, 2:4]  #Aqui lo que hicimos fue tomar la primera y segunda fila y la segunda y tercera columna
#Siempre en forma de L 

array([[104, 121],
       [255, 255]], dtype=uint8)

In [25]:
img_2.shape

(3, 5)

In [27]:
img_2[2,4]  #Aqui buscamos la posición 2 en la fila 4 de la matríz

np.uint8(182)

In [28]:
for i in img_2:  #Imprimimos la matríz
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [31]:
for i in img_2.T:  #Imprimimos la matríz transpuesta
    print(i)
#Es como si la girásemos hacia la derecha

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [33]:
for i in  img_2.flat:  #Imprimimos la matríz por columnas descendentemente
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [34]:
img_2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [38]:
ims = numpy.hstack((img_2, img_2))  #hstack se usa para unir arrays en una sola dimension 
#Es decir unimos dos matrices en una sola

In [39]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [41]:
ims_2 = numpy.hstack((img_2, img_2, img_2))  #Unimos 3 matrices 
print(ims_2)  #Usamos el print para que la matriz se vea mejor

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [44]:
vert = numpy.vstack((img_2, img_2, img_2))
print(vert)  #Imprimimos la matriz verticalmente concatenada

#No se pueden concatenar matrices de diferentes dimensiones

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [50]:
ist = numpy.vsplit(vert,3)  #Est quiere decir que dividimos la matriz en 3 filas puesto que usamos vsplit
ist

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [52]:
ist_2 = numpy.hsplit(vert, 5)  #Aqui se divide la matríz en 5 columnas puesto que usamos hsplit 
ist_2

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [53]:
type(ist)

list

In [55]:
ist[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)