In [ ]:
%pip install pandas

In [2]:
import pandas
import numpy 

n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
type(n)

numpy.ndarray

In [6]:
matrix = n.reshape(3,9)  #Creamos una matriz de 3 x 9
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [ ]:
%pip install opencv-python

In [14]:
import cv2

In [18]:
img_grices = cv2.imread("smallgray.png", 0)  #El cero indica que queremos leer la imagen en escala de grises

In [20]:
img_grices

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
img_rgb = cv2.imread("smallgray.png", 1)  #El argumento 1 es para leer la imagen en rgb

In [24]:
img_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [27]:
cv2.imwrite("newsmallgray.png", img_grices)  #Aqui lo que hicimos fue guardar la imagen en el disco duro

True